Awsbi module
epiphany-platform/m-aws-basic-infrastructure pull request #1
Opened 2020-09-23 14:06 UTC by rafzei

2020-09-24 06:29 UTC, atsikham commented
Could you link/mention an original task?

2020-09-24 10:46 UTC, mkyc requested changes

2020-09-24 10:46 UTC, mkyc commented on resources/terraform/modules/ec2/main.tf
> +	cidr_block        = "10.1.1.0/24"
should we have it variable?

2020-09-24 10:46 UTC, mkyc commented on resources/terraform/modules/ec2/main.tf
> +  cidr_block            = "10.1.0.0/20"
should we have it in variable?

2020-09-24 10:46 UTC, mkyc commented on workdir/Makefile
> +# subtargers
```suggestion
# subtargets
```

2020-09-24 10:56 UTC, mkyc commented
> Could you link/mention an original task?

its [this one](https://github.com/epiphany-platform/epiphany/issues/1637) from main repo

2020-09-24 11:18 UTC, atsikham commented
Is it possible to add requirements information? Such as make, docker, may be something else.

2020-09-24 11:59 UTC, atsikham commented on README.md
> +Prepare your own variables to use in the building process.
IMO it makes sence to describe where to put these vars. Not in sample file, correct?

2020-09-24 12:22 UTC, atsikham requested changes

2020-09-24 12:22 UTC, atsikham commented on README.md
> +all-destroy
make all-destroy

2020-09-24 12:30 UTC, atsikham commented on Makefile
> +
`doesn't exist` ?

2020-09-24 13:09 UTC, atsikham commented on README.md
> +M_VMS_RSA_FILENAME = id_rsa
In this case do we need to change `M_VMS_COUNT ?= 3` in defaults?

2020-09-24 13:18 UTC, atsikham commented on resources/terraform/modules/ec2/main.tf
> +	availability_zone = "${var.region}a"
Only one zone in region supported?

2020-09-24 13:24 UTC, atsikham commented on resources/terraform/versions.tf
> +  #required_version = "0.13.2"
Should it be here?

2020-09-24 14:37 UTC, mkyc commented
> Is it possible to add requirements information? Such as `make`, `docker`, OS, may be something else.

I just created issue #2 for this. 

> 
> Is it supposed to be not able to execute on Windows?
> 
> ```
> PS C:\Users\user\repos\m-aws-basic-infrastructure> make build
> process_begin: CreateProcess(NULL, id -u, ...) failed.
> Makefile:8: pipe: No error
> process_begin: CreateProcess(NULL, id -g, ...) failed.
> Makefile:9: pipe: No error
> ! was unexpected at this time.
> make: *** [Makefile:37: file-guard-Dockerfile] Error 255
> ```

Hmmmm .. I'm unable to test it but can you try [those proposed solutions](https://stackoverflow.com/questions/2532234/how-to-run-a-makefile-in-windows)? If they are too complicated or they do not work, it will be required to test other options. I don't think we should put "build" task into docker container :P

2020-09-24 19:51 UTC, atsikham commented
> > Is it supposed to be not able to execute on Windows?
> > ```
> > PS C:\Users\user\repos\m-aws-basic-infrastructure> make build
> > process_begin: CreateProcess(NULL, id -u, ...) failed.
> > Makefile:8: pipe: No error
> > process_begin: CreateProcess(NULL, id -g, ...) failed.
> > Makefile:9: pipe: No error
> > ! was unexpected at this time.
> > make: *** [Makefile:37: file-guard-Dockerfile] Error 255
> > ```
> 
> Hmmmm .. I'm unable to test it but can you try [those proposed solutions](https://stackoverflow.com/questions/2532234/how-to-run-a-makefile-in-windows)? If they are too complicated or they do not work, it will be required to test other options. I don't think we should put "build" task into docker container :P

I think that the reason is in usage of `id` command. I would detect OS in Makefile and do os specific calls according to result.

2020-09-24 20:03 UTC, mkyc commented
Hmmm ... I didn't consider that we are going to run that on Windows to be fair, but that is good point.

2020-09-25 06:23 UTC, atsikham commented
> Hmmm ... I didn't consider that we are going to run that on Windows to be fair, but that is good point.

If we are not going to do so, we can just note that.

2020-09-25 07:34 UTC, rafzei commented on README.md
> +M_VMS_RSA_FILENAME = id_rsa
@mkyc I don't think forcing users to change variables in source code is good. I prefer the way that all available (well described) variables are in one external config file.

2020-09-25 09:15 UTC, rafzei commented on resources/terraform/modules/ec2/main.tf
> +	availability_zone = "${var.region}a"
It's fine for the initial version of the module

2020-09-25 09:29 UTC, rafzei commented on examples/basic_flow/Makefile
> +M_AMI ?= ami-02ab606eae7264892
@mkyc Should I create a new issue to implement posibility to choose between OSes? or it can be implemented during https://github.com/epiphany-platform/epiphany/issues/1676

2020-09-25 10:38 UTC, rafzei commented
> > Hmmm ... I didn't consider that we are going to run that on Windows to be fair, but that is good point.
> 
> If we are not going to do so, we can just leave a note about that.

It has to be a new issue/spike how we should deal with it.

2020-09-25 12:04 UTC, mkyc commented
Added task in main repo because it's related to all modules.

2020-09-27 18:49 UTC, atsikham requested changes

2020-09-27 18:49 UTC, atsikham commented on resources/defaults.mk
> +M_VMS_COUNT ?= 3
Do we need to set it as 3 by default? It will increase cost for default execution.

2020-09-27 18:49 UTC, atsikham commented on resources/terraform/modules/ec2/main.tf
> +    "AWS::StorageGateway::Gateway"
How members of this list were selected? Not all resources are listed, at least EC2 - https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html#services-ec2

2020-09-27 18:49 UTC, atsikham commented on resources/terraform/modules/ec2/main.tf
> +  	cluster_name = var.name
Need to check all indents

2020-09-27 18:49 UTC, atsikham commented on resources/terraform/modules/ec2/main.tf
> +    Name = var.name
does `cluster_name` supposed to be here?

2020-09-27 18:49 UTC, atsikham commented on resources/terraform/modules/ec2/main.tf
> +  security_groups             = [
Please check [this](https://github.com/hashicorp/terraform/issues/14416#issuecomment-302744479) link. Using such parameter probably will recreate instance for each `terraform apply`.

2020-09-27 18:49 UTC, atsikham commented on resources/terraform/provider.tf
> +  version = "3.7.0"
In the [doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#example-usage) this version defined in another place.

2020-09-28 13:25 UTC, rafzei commented on resources/defaults.mk
> +M_VMS_COUNT ?= 3
We can set it to '1' so it's more cost efficient in case someone wants to run it just to get familiar with the module or test something w/o any reconfiguration.

2020-09-28 13:45 UTC, rafzei commented on resources/terraform/modules/ec2/main.tf
> +    "AWS::StorageGateway::Gateway"
It was copy-pasted from our current tf code. I will refactor it and align it to the used resources.

2020-09-28 14:42 UTC, rafzei commented on resources/terraform/modules/ec2/main.tf
> +  	cluster_name = var.name
hashicorp/aws

2020-09-28 14:43 UTC, rafzei commented on resources/terraform/modules/ec2/main.tf
> +  	cluster_name = var.name
There is something weird with that indentation. In my local VSC its fine.

2020-09-28 14:47 UTC, atsikham commented on resources/terraform/modules/ec2/main.tf
> +  	cluster_name = var.name
```suggestion
    cluster_name = var.name
```

2020-09-28 20:04 UTC, rafzei commented on resources/terraform/modules/ec2/main.tf
> +  	cluster_name = var.name
Thanks!

2020-09-28 22:41 UTC, atsikham requested changes

2020-09-28 22:41 UTC, atsikham commented on resources/defaults.mk
> +
The number of values here is less than in `variables.tf`. How to pass `vpc_cidr_block` to terraform configuration?

2020-09-29 07:41 UTC, atsikham commented on resources/terraform/main.tf
> +  }
indent

2020-09-29 07:43 UTC, atsikham commented on resources/terraform/output.tf
> +}
Are IPs necessary in output?

2020-09-29 07:49 UTC, atsikham commented on resources/terraform/versions.tf
> +  required_version = "0.13.2"
@mkyc Probably in future we will have common base image/dockerfile for all/some modules, and when we change terraform version it'll require manual changes in every module.

2020-09-29 08:05 UTC, rafzei commented on resources/terraform/output.tf
> +}
It's the easiest way to get this information after the successful deployment. For now, I'm not sure if any further modules will use it.

2020-09-29 08:09 UTC, atsikham approved these changes
I left some comments, but in general LGTM.

2020-09-29 08:09 UTC, rafzei commented on resources/terraform/versions.tf
> +  required_version = "0.13.2"
@atsikham @mkyc we can put there grater or equal but we don't know if our code will be still valid for the next tf versions.

2020-09-29 08:11 UTC, atsikham commented on resources/terraform/versions.tf
> +  required_version = "0.13.2"
Agree, that's a thing to think about.

2020-09-29 13:15 UTC, mkyc approved these changes
LGTM

2020-09-29 13:22 UTC, mkyc commented on resources/terraform/versions.tf
> +  required_version = "0.13.2"
I believe strictly bumping versions is always good thing

2020-09-29 13:25 UTC, mkyc commented on resources/terraform/output.tf
> +}
machines public IPs will be required by epicli to access them during Epiphany installation.

2020-09-30 06:21 UTC, merged