Added devcontainer.
epiphany-platform/m-aws-basic-infrastructure pull request #13
Opened 2020-10-06 14:27 UTC by seriva

Useful for the poor people using Windows. Similar to https://github.com/epiphany-platform/m-azure-basic-infrastructure/pull/17

2020-10-08 19:37 UTC, rafzei requested changes
To run it, I had to do the following changes.

2020-10-08 19:37 UTC, rafzei commented on examples/basic_flow_devcontainer/Makefile
> +-include "$(ROOT_DIR)/vars.mk"
```suggestion
-include $(ROOT_DIR)/vars.mk
```

2020-10-08 19:37 UTC, rafzei commented on examples/basic_flow_devcontainer/Makefile
> +setup: $(M_SHARED)/shared/$(M_VMS_RSA_FILENAME)
```suggestion
setup: $(M_SHARED)/$(M_VMS_RSA_FILENAME)
```

2020-10-08 19:37 UTC, rafzei commented on examples/basic_flow_devcontainer/Makefile
> +$(M_SHARED)/shared/$(M_VMS_RSA_FILENAME):
```suggestion
$(M_SHARED)/$(M_VMS_RSA_FILENAME):
```

2020-10-08 19:37 UTC, rafzei commented on examples/basic_flow_devcontainer/Makefile
> +	@cd $(M_WORKDIR) && $(MAKE) metadata \
```suggestion
	@cd $(M_WORKDIR) && $(MAKE) metadata
```

2020-10-09 09:54 UTC, rafzei approved these changes
One more thing:
setup-env.sh file should have execution rights (only matter on linux env)

2020-10-10 21:22 UTC, atsikham approved these changes

2020-10-12 06:58 UTC, merged