Increase default root disk size
epiphany-platform/m-aws-basic-infrastructure pull request #24
Opened 2020-10-21 09:51 UTC by atsikham

2020-10-21 17:20 UTC, mkyc requested changes

2020-10-21 17:20 UTC, mkyc commented on CHANGELOG/0.0.1.md
> +* [#21](https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/21) - Add the ability to extend root disk size
[0.0.1 is already released](https://github.com/epiphany-platform/m-aws-basic-infrastructure/releases/tag/v0.0.1), please move it to another file named 0.0.2

2020-10-21 17:20 UTC, mkyc commented on resources/terraform/modules/ec2/main.tf
> +    volume_size = var.root_disk_size
```suggestion
    volume_size = var.root_volume_size
```

2020-10-21 17:20 UTC, mkyc commented on resources/terraform/main.tf
> +  root_disk_size    = var.root_disk_size
```suggestion
  root_volume_size    = var.root_volume_size
```

2020-10-21 17:20 UTC, mkyc commented on resources/terraform/modules/ec2/variables.tf
> +  description = "The size of the volume in gibibytes (GiB)"
```suggestion
variable "root_volume_size" {
  description = "The size of the root volume in gibibytes (GiB)"
```

2020-10-21 17:20 UTC, mkyc commented on resources/terraform/variables.tf
> +  description = "The size of the volume in gibibytes (GiB)"
```suggestion
variable "root_volume_size" {
  description = "The size of the root volume in gibibytes (GiB)"
```

2020-10-22 11:43 UTC, erzetpe approved these changes

2020-10-22 12:05 UTC, mkyc approved these changes
LGTM

2020-10-22 12:06 UTC, merged