Feature/automatic integration tests
epiphany-platform/m-aws-basic-infrastructure pull request #25
Opened 2020-10-21 12:16 UTC by erzetpe

2020-11-03 15:55 UTC, atsikham requested changes
I have a few questions/suggestions after review:
* Have you changed pipeline to execute new tests
* Is it possible to run tests in parallel? I mean if 2 pipelines are running at the same time for 2 different PRs, or if someone ran tests manually. We need to prevent failures in this case.
* Too much commented code, it shouldn't be so.
* Could you update licenses with new libs/tools/frameworks information?

2020-11-03 15:55 UTC, atsikham commented on CHANGELOG/0.0.2.md
> +* [#1676](https://github.com/epiphany-platform/epiphany/issues/1676) Initial automatic tests for AWS basic infrastructure module
```suggestion
* [#1676](https://github.com/epiphany-platform/epiphany/issues/1676) - Initial automatic tests for AWS basic infrastructure module
```

2020-11-03 15:55 UTC, atsikham commented on CHANGELOG/0.0.2.md
> +* [#1676](https://github.com/epiphany-platform/epiphany/issues/1676) Initial automatic tests for AWS basic infrastructure module
It can be declined, but let's decide now and follow one style.

2020-11-03 15:55 UTC, atsikham commented on tests/integration_test.go
> +// }
Let's delete?

2020-11-03 15:55 UTC, atsikham commented on tests/integration_test.go
> +	imageTag   = "epiphanyplatform/awsbi:0.0.1"
For the each pipeline run do you execute tests from image that are outdated or latest ones? See similar issues:
* https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/37
* https://github.com/epiphany-platform/m-azure-basic-infrastructure/issues/38

2020-11-03 19:08 UTC, erzetpe commented on tests/integration_test.go
> +// }
You have started review, before I have pushed changes. :)

2020-11-05 10:10 UTC, seriva commented
ALso pls at everything in root like @mkyc did for his tests so everything is similar across these modules.

2020-11-05 15:05 UTC, mkyc requested changes
Could you also fix pipeline.yml to run this test actually?

2020-11-06 10:10 UTC, atsikham commented
Please update requirements.md with all software necessary to run tests.

2020-11-06 14:17 UTC, erzetpe commented on tests/integration_test.go
> +	moduleName = "awsbi-module"
We can have different tags than module name, this can be useful for testing purose.

2020-11-06 14:35 UTC, erzetpe commented on tests/integration_test.go
> +	var stdout, stderr bytes.Buffer
As we discussed we can just assign this at the usage.

2020-11-06 17:20 UTC, atsikham commented on README.md
> +<<<<<<< HEAD
?

2020-11-06 17:20 UTC, atsikham commented on README.md
> +>>>>>>> b35799e... Add short introduction for testing to README
?

2020-11-09 13:02 UTC, erzetpe commented on tests/integration_test.go
> +	}
Solved different way that suggested.

2020-11-09 13:03 UTC, erzetpe commented on tests/integration_test.go
> +	}
Will create issue for this.

2020-11-09 14:30 UTC, mkyc requested changes
Still ... do you plan to fix pipelines.yml in that PR?

2020-11-09 14:30 UTC, mkyc commented on tests/integration_test.go
> +	rgResourcesList, err := rgClient.ListGroupResources(&resourcegroups.ListGroupResourcesInput{
unhandled err

2020-11-09 14:30 UTC, mkyc commented on tests/integration_test.go
> +	session, err := session.NewSession(&aws.Config{Region: aws.String(awsRegion)})
```suggestion
	newSession, err := session.NewSession(&aws.Config{Region: aws.String(awsRegion)})
```
collides with imported package name

2020-11-09 14:30 UTC, mkyc commented on tests/integration_test.go
> +		outDesc, errDesc := ec2Client.DescribeNatGateways(descInp)
unhandled other types of errDesc errors

2020-11-09 14:30 UTC, mkyc commented on tests/integration_test.go
> +func TestShouldCheckNumberOfVms(t *testing.T) {
Hmmm do I understand correctly, that this test checks if there is 1 machine without creating it? How does it work then? It's called cater cleanup functions so there should be no machines?

2020-11-09 14:30 UTC, mkyc commented on tests/integration_test.go
> +		t.Fatal("Cannot get session.")
```suggestion
		t.Fatal(err)
```

2020-11-09 14:30 UTC, mkyc commented on tests/integration_test.go
> +		t.Fatal("Cannot read state file: ", stateFilePath)
```suggestion
		t.Fatal(err)
```

2020-11-10 10:49 UTC, mkyc submitted a review, later dismissed
I believe it's good enough for first version

2020-11-10 11:10 UTC, atsikham commented
Please don't merge, I would like to review first.

2020-11-10 11:20 UTC, atsikham requested changes
Almost LGTM, but please take care of documentation part, add comments to go tests to be able to use [godoc](https://blog.golang.org/godoc) (I bet that in future nobody will add it with low priority task) and clarify the status of related changes in pipelines - if it isn't there, another task should be created.

2020-11-10 11:20 UTC, atsikham commented on README.md
> +This module is designed for Linux/Unix development/usage only. If you need to develop from Windows you can use the included [devcontainer setup for VScode](https://code.visualstudio.com/docs/remote/c
This part has been already moved to another [place](https://github.com/epiphany-platform/m-aws-basic-infrastructure/blob/develop/docs/REQUIREMENTS.md#operating-systems).

Please also update:
* [licenses](https://github.com/epiphany-platform/m-aws-basic-infrastructure/blob/develop/README.md#module-dependencies) in readme with tools/frameworks you used for tests;
* [requirements](https://github.com/epiphany-platform/m-aws-basic-infrastructure/blob/develop/docs/REQUIREMENTS.md#execute-module-tests) that are necessary to run tests locally.

2020-11-10 14:34 UTC, rafzei commented on README.md
> +## Integration tests execution
@erzetpe What do you think about adding a new file in docs/TESTS.md and point it here?

2020-11-10 14:41 UTC, atsikham commented on README.md
> +## Integration tests execution
@rafzei imo it could left here with created `TESTS.md` file (or any preferred name) with reference to `REQUIREMENTS.md` and it could reduce size of `README.md` by placement related part in `TESTS.md`. It would allow to have all requirements in one place.

2020-11-10 15:33 UTC, erzetpe commented on README.md
> +## Integration tests execution
We will think later on what to do with this documentation when tests will grow.

2020-11-10 15:36 UTC, mkyc approved these changes

2020-11-10 15:36 UTC, merged