initial pipeline test yaml #1761
epiphany-platform/m-aws-basic-infrastructure pull request #32
Opened 2020-11-03 16:59 UTC by ar3ndt

2020-11-04 10:34 UTC, atsikham requested changes
A few points to discuss/change:
* Where is test results publishing? Or it's not generated in this module?
* Please use `displayName` for jobs and use more descriptive job names, as we discussed.
* Do not forget disable old pipelines in UI.

2020-11-09 08:51 UTC, ar3ndt commented
> A few points to discuss/change:
> 
> * Where is test results publishing? Or it's not generated in this module?
> * Please use `displayName` for jobs and use more descriptive job names, as we discussed.
> * Do not forget disable old pipelines in UI.

reports are not generated for now afaik

2020-11-09 14:42 UTC, atsikham approved these changes
For me changes are ok. Contact @to-bar if job names are ok for him.

2020-11-10 20:43 UTC, mkyc requested changes
After PR #25 this one should definitely look [more like this](https://github.com/epiphany-platform/m-azure-basic-infrastructure/blob/develop/pipeline.yml)

2020-11-16 08:03 UTC, atsikham requested changes

2020-11-16 08:03 UTC, atsikham commented on pipeline.yml
> +            export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
Is it possible to replace env related lines in [this](https://github.com/epiphany-platform/m-azure-basic-infrastructure/blob/a72f72aea681483ef3bf56873246a0d3e4993393/pipeline.yml#L36) way?

2020-11-18 12:12 UTC, mkyc commented
Move source branch to epiphany repo. Otherwise Azure DevOps would not be able to run tests correctly.

2020-11-24 09:01 UTC, atsikham approved these changes

2020-11-24 09:41 UTC, mkyc commented
> Move source branch to epiphany repo. Otherwise Azure DevOps would not be able to run tests correctly.

Haven't seen it reported even once. And reason is wrong source.

2020-11-24 10:51 UTC, closed without merging

2020-11-24 10:51 UTC, ar3ndt commented
moved to source repo