Updated documentation
epiphany-platform/m-aws-basic-infrastructure pull request #34
Opened 2020-11-04 12:41 UTC by atsikham

PR that is related to #2 task

2020-11-04 15:12 UTC, erzetpe approved these changes

2020-11-06 07:36 UTC, rafzei requested changes

2020-11-06 07:36 UTC, rafzei commented on docs/INPUTS.adoc
> +== Input parameters
Please add "steps" like in [this PR](https://github.com/epiphany-platform/m-aws-kubernetes-service/pull/21)
And this doc can be linked in section "Plan and apply AwsBI module:" as well.

2020-11-06 09:38 UTC, atsikham commented on docs/INPUTS.adoc
> +== Input parameters
Added, please check. For plan and apply it's not necessary to add a link, as description in readme is enough in this case.

2020-11-06 09:58 UTC, rafzei approved these changes

2020-11-06 10:09 UTC, erzetpe approved these changes

2020-11-06 10:09 UTC, merged