Additional subnets
epiphany-platform/m-aws-basic-infrastructure pull request #40
Opened 2020-11-17 13:44 UTC by atsikham

2020-11-17 14:34 UTC, mkyc commented
PR #32 has to be merged before this PR.

2020-11-17 14:55 UTC, mkyc commented
Regarding draft PR description: 
 - Comment from @pprach would be helpful: do we need to specify subnets ranges manually or is that ok to calculate them automatically (at least for now). 
 - but I think, that moving `vms_count` to subnets (to indicate how many machines we want in each subnet) would be required

I'm not sure about #20 and networking part in AWSKS, that would require some discussion.

2020-11-17 15:04 UTC, atsikham commented
> Regarding draft PR description:
> 
> * Comment from @pprach would be helpful: do we need to specify subnets ranges manually or is that ok to calculate them automatically (at least for now).
> * but I think, that moving `vms_count` to subnets (to indicate how many machines we want in each subnet) would be required
> 
> I'm not sure about #20 and networking part in AWSKS, that would require some discussion.

* I would calculate CIDR ranges automatically unless we have no such requirement.
* But we are also going to implement [VM groups](https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/27#issuecomment-728776603), where subnets will be specified. In this case I think your second point conflicts with that task.

2020-11-18 12:11 UTC, mkyc commented
is `count` in:
```
 private: [
    {count: `num`, availability_zone: `az_name` or `any`, net_bits: `num`},
    ...
  ],
```

number of machines in this private subnet, or number of such subnets? Can you rename that variable to something more descriptive?

2020-11-18 13:14 UTC, atsikham commented
@mkyc modified, it's the number of subnets with the same AZ and [newbits](https://registry.terraform.io/modules/hashicorp/subnets/cidr/latest#new_bits) parameters

2020-11-18 15:02 UTC, mkyc commented
How will I define how many machines I want in each subnet?

2020-11-18 15:17 UTC, atsikham commented
> How will I define how many machines I want in each subnet?

This is defined by the third parameter in a map (`subnet_address_bits` for example). Assuming you have `VPC CIDR block` defined to `10.1.0.0/20` and `subnet_address_bits` `4`, so there are 8 bits left for hosts and in case of AWS it's 251 host.

2020-11-18 16:03 UTC, atsikham commented
> I meant `M_VMS_COUNT` parameter described [here](https://github.com/epiphany-platform/m-aws-basic-infrastructure/blob/develop/docs/INPUTS.adoc). So how will I force AwsBI module to put machines in those new subnets?

At the moment I placed them to public/private subnets depending on `use_public_ip` parameter, with round-robin assignement. I think this sould be implemented in #27 the way @sk4zuzu suggested. But in general I see what you are talking about - we need some identifier to place VM into subnet. But isn't it enough to specify AZ to place vm in and select any subnet from there?

2020-11-18 23:39 UTC, mkyc commented
As far as I understand we are talking about direction of relation (vm group in subnet or subnet in vm group). My opinion is that we want to put vm groups in subnets. 

In @sk4zuzu [comment](https://github.com/epiphany-platform/m-aws-basic-infrastructure/issues/27#issuecomment-728776603):

```
define subnet(s) for the group, but it should be also possible to span multiple groups across single subnet 
```

I tend to focus more on `span multiple groups across single subnet` part of sentence. That indicates rather vm groups in subnets. 


BTW: do you consider move of that "module" code to root terraform directory? It feels like overhead.

2020-11-19 12:26 UTC, atsikham commented
This request is blocked by #32, but let's review and make changes when new requirements appear.

2020-11-19 14:32 UTC, mkyc commented
Let's have this move in separate task, not to overcomplicate this one.

2020-11-24 14:49 UTC, mkyc commented
@atsikham please rerun tests as #41 was merged.

2020-11-24 15:26 UTC, atsikham commented
/azp run

2020-11-24 15:38 UTC, atsikham commented
/azp run

2020-11-25 15:34 UTC, atsikham commented
/azp run

2020-11-26 15:23 UTC, erzetpe requested changes

2020-11-26 15:23 UTC, erzetpe commented on tests/integration_test.go
> +	    t.Log("Stdout: ", string(stdout.Bytes()))
At least this should be taken out of this if section.

2020-11-26 16:15 UTC, erzetpe approved these changes

2020-11-27 09:33 UTC, mkyc commented
@sk4zuzu can you also confirm that this PR solves #20?

2020-11-27 10:34 UTC, sk4zuzu submitted a review, later dismissed
Looks correct. Clock arithmetic is in place. If there are less NGs than AZs all remaining are reused correctly. I believe this is the HA (#20) that we want. :+1:

2020-11-27 10:34 UTC, sk4zuzu commented on resources/terraform/modules/ec2/variables.tf
> +    condition     = var.subnets.private.count > 0 || var.subnets.public.count > 0
Does it make sense to have only private subnets without Internet access? What would be the use case? :thinking: 
```suggestion
    condition     = (var.subnets.private.count > 0 && var.subnets.public.count > 0) || var.subnets.public.count > 0
```

2020-11-27 11:07 UTC, atsikham commented on resources/terraform/modules/ec2/variables.tf
> +    condition     = var.subnets.private.count > 0 || var.subnets.public.count > 0
Discussed with @sk4zuzu that having private subnet implies that you need public one as well.

2020-11-27 11:23 UTC, sk4zuzu approved these changes

2020-11-27 11:25 UTC, mkyc submitted a review, later dismissed

2020-11-27 11:57 UTC, sk4zuzu commented on docs/INPUTS.adoc
> +that a created in available AZs with round-robin
Is this a typo? :thinking: 
```suggestion
that are created in available AZs with round-robin
```

2020-11-27 11:59 UTC, erzetpe approved these changes

2020-11-27 12:01 UTC, sk4zuzu approved these changes
:monkey:

2020-11-27 12:03 UTC, mkyc approved these changes
LGTM

2020-11-27 12:05 UTC, merged