Ability to specify subnet details
epiphany-platform/m-aws-basic-infrastructure pull request #51
Opened 2021-01-11 15:16 UTC by rpudlowski93

- Added ability to specify subnet details
- Related to task #43
- Until now we could only specify number of subnets which we would like to create
- After merge of this PR we could specify list of subnets (private and public) with unique names, we could specify also address space of VPC and address prefixes of each subnet and we could specify availability zone for each subnet or choose "any" in order to chose random one which is available in the region.

2021-01-12 08:40 UTC, atsikham requested changes

2021-01-12 08:40 UTC, atsikham commented on docs/INPUTS.adoc
> +|M_SUBNETS |list(object)
```suggestion
|M_SUBNETS |list(map)
```

2021-01-12 08:40 UTC, atsikham commented on resources/defaults.mk
> +    }]
check line indents

2021-01-12 08:40 UTC, atsikham commented on resources/terraform/modules/ec2/variables.tf
> +    condition     = (length(var.subnets.private) > 0 && length(var.subnets.public) > 0) || length(var.subnets.public)> 0
```suggestion
    condition     = (length(var.subnets.private) > 0 && length(var.subnets.public) > 0) || length(var.subnets.public) > 0
```

2021-01-12 08:40 UTC, atsikham commented on resources/terraform/modules/ec2/locals.tf
> +  private_subnet_numbers    = length(var.subnets.private)
Both locals can be removed, no need a separate variable for such values

2021-01-12 08:40 UTC, atsikham commented on resources/defaults.mk
> +    }],
check line indents

2021-01-12 08:40 UTC, atsikham commented on CHANGELOG/0.0.3.md
> +### Fixed
I see that there is no 0.0.2 release, please check that it should be so - https://github.com/epiphany-platform/m-aws-basic-infrastructure/releases

2021-01-12 09:26 UTC, rpudlowski93 commented on CHANGELOG/0.0.3.md
> +### Fixed
Release date in changelog 0.0.2 totally mislead me... I will remove it

2021-01-12 11:55 UTC, atsikham approved these changes

2021-01-14 13:08 UTC, mkyc approved these changes
LGTM

2021-01-14 13:08 UTC, mkyc commented
/azp run

2021-01-18 11:57 UTC, merged