Ability to create VM groups
epiphany-platform/m-aws-basic-infrastructure pull request #56
Opened 2021-02-19 23:45 UTC by rpudlowski93

PR related to #27,  #55, #37
- Possibility to create VM group added: 
- Possibility to create VPC with a single public subnet or VPC with public and private subnets (NAT) or VPC with public and private subnets (without NAT) or VPC with only private subnets, added
- Possibility to customise data disks per VM group added
- Possibility to customise security group per VM group added
- Possibility to enable/disable public IPs per VM group added
- Possibility to define instance count and size per VM group added
- Possibility to set vm image specification per VM group added

2021-02-24 12:52 UTC, atsikham requested changes
Besides that points that I mentioned:

* In the task #55 I see the reference to the scenario with a VPN gateway, but don't see here `aws_vpn_gateway` resource creation, also there is no anything like parameter mentioned in the task `private_cluster: true/false`
* I think it's a time to have a more detailed configuration for NAT gateways, not round-robin creation, with specifying in which public subnet it's located and for which private subnets it will be used - just an idea for an additional task.

2021-02-24 12:52 UTC, atsikham commented on resources/terraform/modules/vm_group/main.tf
> +  subnet_id                   = element(data.aws_subnet.selected.*.id, count.index)
Nice place to think about.. This behaviour attaches each EC2 instance into a single subnet using round-robin, but in AWS both resources, instances and subnets are zonal, and right now I don't see the reason to do it somehow else.

After reviewing this place I realized that we don't use network ACLs. For example, we have 3 VM groups corresponding to 3 applications: Kafka, app1, app2. We don't have a mechanism to somehow specify that app2 shouldn't access Kafka or vice versa. Security group does not support "deny" rules, but it's possible to do with network ACLs:

* https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html#VPCSecurityGroups
* https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Security.html#VPC_Security_Comparison
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_acl

WDYT about a separate task for that?

2021-02-24 12:52 UTC, atsikham commented on resources/terraform/modules/vm_group/main.tf
> +resource "aws_ebs_volume" "data_disks" {
I was thinking about specifying it directly in `aws_instance` resource, but there is one important note in the [doc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#ebs-ephemeral-and-root-block-devices):

```
Currently, changes to the ebs_block_device configuration of existing resources cannot be automatically detected by Terraform. To manage changes and attachments of an EBS block to an instance, use the aws_ebs_volume and aws_volume_attachment resources instead. If you use ebs_block_device on an aws_instance, Terraform will assume management over the full set of non-root EBS block devices for the instance, treating additional block devices as drift. For this reason, ebs_block_device cannot be mixed with external aws_ebs_volume and aws_volume_attachment resources for a given instance.
```

2021-02-24 15:43 UTC, rpudlowski93 commented on resources/terraform/modules/vm_group/main.tf
> +    values = ["${var.vm_group.subnet_names[count.index]}"]
Good idea but in this case it won't work: 
Error: multiple subnets matched; use additional constraints to reduce matches to a single subnet

2021-02-24 16:10 UTC, rpudlowski93 commented on resources/terraform/main.tf
> +  depends_on = [aws_subnet.awsbi_public_subnet]
True, first bug :)

2021-02-24 16:11 UTC, rpudlowski93 commented on resources/defaults.mk
> -M_OS ?= redhat
Sure, I will add to documentation which version we support and is tested.

2021-02-25 13:21 UTC, atsikham commented on resources/terraform/modules/vm_group/main.tf
> +  subnet_id                   = element(data.aws_subnet.selected.*.id, count.index)
@mkyc here is the place that we talked about last time

2021-02-25 14:06 UTC, rpudlowski93 commented on resources/defaults.mk
> -M_OS ?= redhat
Documentation updated. I don't want to create additional parameters such as private_cluster since the code will be overloaded. It is enough to create ONLY private subnets what means private cluster. Adding the additional parameters won't help users, won't reduce our code. User must be conscious what he does and what he needs in order to achieve proper cluster.

2021-02-25 14:07 UTC, rpudlowski93 commented
> Besides that points that I mentioned:
> 
> * In the task #55 I see the reference to the scenario with a VPN gateway, but don't see here `aws_vpn_gateway` resource creation, also there is no anything like parameter mentioned in the task `private_cluster: true/false`
> * I think it's a time to have a more detailed configuration for NAT gateways, not round-robin creation, with specifying in which public subnet it's located and for which private subnets it will be used - just an idea for an additional task.

After short discussion with experienced guys in AWS, possibility to create vpn gateway added. I don't want to create additional parameters such as private_cluster since the code will be overloaded. It is enough to create ONLY private subnets what means private cluster. Adding the additional parameters won't help users, won't reduce our code. User must be conscious what he does and what he needs in order to achieve proper cluster.

2021-02-25 14:09 UTC, rpudlowski93 commented on resources/terraform/modules/vm_group/main.tf
> +resource "aws_ebs_volume" "data_disks" {
I also read the doc and I suggest to stay as it is right now.

2021-02-25 14:12 UTC, erzetpe submitted a review, later dismissed

2021-02-25 14:27 UTC, atsikham requested changes

2021-02-25 14:27 UTC, atsikham commented on resources/terraform/locals.tf
> +  use_virtual_private_gateway = (length(var.subnets.private) > 0 && var.nat_gateway_count == 0 && var.virtual_private_gateway)
If both `virtual_private_gateway` is `true` and `nat_gateway_count` > 0, they will not be created. I suggest not to add related validation here and allow user to create resources that he/she specified.

2021-02-25 14:55 UTC, mkyc commented on resources/terraform/modules/vm_group/main.tf
> +  subnet_id                   = element(data.aws_subnet.selected.*.id, count.index)
Thanks, I didn't noticed it previously. We might use this code as it is right now and wait for additional requirements from middleware modules. I think we need to come back to design board later to discuss exactly what we want to have. This current solution is good enough for now I believe.

2021-02-25 15:22 UTC, rpudlowski93 commented on resources/terraform/locals.tf
> +  use_virtual_private_gateway = (length(var.subnets.private) > 0 && var.nat_gateway_count == 0 && var.virtual_private_gateway)
Generally, Nat Gateway and VP Gateway shouldn't be created together so I created the validation, but I can remove it indeed since terraform already check it so I'm happy :) 

`
Error: Error creating route: InvalidParameterCombination: The request must contain exactly one of gatewayId, natGatewayId, networkInterfaceId, vpcPeeringConnectionId, egressOnlyInternetGatewayId, transitGatewayId, localGatewayId or instanceId
        status code: 400, request id: 33def212-1673-4005-90c9-fd638e9996fe`

2021-02-25 15:29 UTC, atsikham approved these changes

2021-02-25 17:35 UTC, erzetpe approved these changes

2021-02-25 20:21 UTC, merged