rewrite to go
epiphany-platform/m-aws-basic-infrastructure pull request #65
Opened 2021-05-12 12:17 UTC by mkyc

2021-05-25 14:18 UTC, mkyc commented
/azp run

2021-05-26 16:06 UTC, seriva submitted a review, later dismissed

2021-06-07 12:23 UTC, atsikham requested changes
Shouldn't examples/basic_flow be removed? Or it will be done later in the scope of other work?

2021-06-07 12:23 UTC, atsikham commented on cmd/init.go
> +	initCmd.Flags().String("vms_rsa", "vms_rsa", "name of rsa keypair to be provided to machines")
I would choose --vms-rsa, but up to you

2021-06-07 12:23 UTC, atsikham commented on docs/DEVELOPMENT.md
> +1) run module init command ie.: `docker run --rm -v $(pwd)/shared:/shared -t epiphanyplatform/awsbi:dev init`
i.e.

2021-06-07 12:23 UTC, atsikham commented on resources/terraform/modules/vm_group/output.tf
> +      private_ip: vm.private_ip
So don't we support a few private IPs for 1 VM?

2021-06-07 13:48 UTC, mkyc commented on resources/terraform/modules/vm_group/output.tf
> +      private_ip: vm.private_ip
code didn't support anyways. I just changed name of variable to reflect value retrieved from vm. I also checked terraform resource and it is clear that it has one IP. We probably should extract it to separate issue.

2021-06-07 13:49 UTC, mkyc commented on Dockerfile
> +FROM golang:1.15.2 as builder
I don't want to update all versions here. This PR is big enough. I will exclude it to separate issue.

2021-06-07 13:49 UTC, mkyc commented on Dockerfile
>  FROM hashicorp/terraform:0.13.2 as initializer
same as above

2021-06-07 13:50 UTC, mkyc commented on Dockerfile
> +FROM golang:1.15.2 as builder
added #67

2021-06-07 13:52 UTC, mkyc commented on Dockerfile
>  FROM hashicorp/terraform:0.13.2 as initializer
also referenced in #67

2021-06-07 13:56 UTC, mkyc commented on resources/terraform/modules/vm_group/output.tf
> +      private_ip: vm.private_ip
created #68

2021-06-07 14:01 UTC, atsikham approved these changes

2021-06-08 06:45 UTC, seriva approved these changes

2021-06-08 07:03 UTC, merged